<?php

use craft\base\Plugin as BasePlugin;

class Plugin extends BasePlugin
{
    /**
     * @inheritDoc
     */
    public string $schemaVersion = '1.0.0';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}