<?php

namespace pdaleramirez\commercepaymongo;

use craft\base\Plugin as BasePlugin;
use craft\commerce\services\Gateways;
use craft\commerce\stripe\gateways\PaymentIntents;
use craft\events\RegisterComponentTypesEvent;
use pdaleramirez\commercepaymongo\gateways\PayMongo;
use yii\base\Event;

class Plugin extends BasePlugin
{
    /**
     * @inheritDoc
     */
    public string $schemaVersion = '1.0.0';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        Event::on(
            Gateways::class,
            Gateways::EVENT_REGISTER_GATEWAY_TYPES,
            function(RegisterComponentTypesEvent $event) {
                $event->types[] = PayMongo::class;
            }
        );
    }
}